# Basic site settings
site_name: "Example Doasdasdsadcumentation"
site_description: "A compasdasdrehensive guide for Example Documentation"
site_author: "Your sadasdasdName"

# Repository links for editing and viewing the docs
repo_url: https://github.com/moonsol124/doc-test
edit_uri: edit/main/myDocs # Adjust path if your docs are in a different directory in the repo

# Custom docs directory
docs_dir: myDocs # This specifies the directory containing your Markdown files

# Navigation structure for the documentation site
nav:
  - Home:
      - This is some Test: "Home/test.md"

# Plugins to enhance MkDocs functionality
plugins:
  - techdocs-core # Essential for integrating with Backstage TechDocs
  - search # Built-in search functionality
