# Basic site settings
site_name: "Example Doasdasdsadcumentation"
site_description: "A compasdasdrehensive guide for Example Documentation"
site_author: "Your sadasdasdName"

# Repository links for editing and viewing the docs
repo_url: https://github.com/moonsol124/doc-test
edit_uri: edit/main/myDocs # Adjust path if your docs are in a different directory in the repo

# Custom docs directory
docs_dir: myDocs # This specifies the directory containing your Markdown files

# Navigation structure for the documentation site
nav:
  - Overview:
      - What is Backstage?: "overview/what-is-backstage.md"
      - Architecture overview: "overview/architecture-overview.md"
      - Project Roadmap: "overview/roadmap.md"
      - Vision: "overview/vision.md"
      - The Spotify Story: "overview/background.md"
      - Strategies for adopting: "overview/adopting.md"
      - Release & Versioning Policy: "overview/versioning-policy.md"
      - Backstage Threat Model: "overview/threat-model.md"
      - Support and community: "overview/support.md"
      - Logo assets: "overview/logos.md"

# Plugins to enhance MkDocs functionality
plugins:
  - techdocs-core # Essential for integrating with Backstage TechDocs
  - search # Built-in search functionality
